# Generated by Django 5.1.2 on 2024-10-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CultivationPlanFertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.cultivationplan')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.fertilizer')),
            ],
        ),
    ]
