# Generated by Django 5.1.2 on 2024-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=32)),
                ('scientific_name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=32, null=True)),
                ('acquisition_date', models.DateField()),
            ],
        ),
    ]
