# Generated by Django 5.1.2 on 2024-10-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alias',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
