# Generated by Django 5.1.2 on 2024-10-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='name',
        ),
    ]
