# Generated by Django 5.1.2 on 2024-10-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0002_cultivationplan_cultivationplanfertilizer'),
        ('plants', '0003_rename_plant_name_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cultivation_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='fertilizers.cultivationplan'),
        ),
    ]
